version: '3'
services:
        web:
                image: flask_movie_database_v1
                build: .
                ports:
                        - "8765:8765"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
